version: 1

run:
  timeout: 4m

linters-settings:
  depguard:
    include-go-root: true
    reject:
      - io/ioutil
    ignore-generated: true
    exclude-go-tests: false

  gci:
    custom-order:
      - std
      - default
      - prefix(github.com/dexidp/dex)

  goimports:
    local-prefixes: github.com/dexidp/dex

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - exhaustive
    - exportloopref
    - gci
    - gochecknoinits
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace


        # Disable temporarily until everything works with Go 1.18
        # - typecheck

        # TODO: fix linter errors before enabling
        # - exhaustivestruct
        # - gochecknoglobals
        # - errorlint
        # - gocognit
        # - godot
        # - nlreturn
        # - noctx
        # - wrapcheck

        # TODO: fix linter errors before enabling (from original config)
        # - dupl
        # - errcheck
        # - goconst
        # - gocyclo
        # - gosec
        # - lll
        # - scopelint

        # unused
        # - goheader
        # - gomodguard

        # don't enable:
        # - asciicheck
        # - funlen
        # - godox
        # - goerr113
        # - gomnd
        # - interfacer
        # - maligned
        # - nestif
        # - testpackage
        # - wsl
